import type {
  Error as APNsError,
  ErrorData,
  LibraryFailedItem,
  LibrarySentItem,
  RawResponse,
  SentDetail,
} from '$generated/types';

// Types not yet generated by type-crafter (contain $ref/arrays/oneOf)
// TODO: Remove these once type-crafter generates them

export interface LibraryResult {
  failed: LibraryFailedItem[] | null;
  sent: LibrarySentItem[] | null;
}

export interface NotificationPayload {
  badge: null | number;
  body: null | string;
  category?: null | string;
  data: null | Record<string, unknown>;
  message: null | string;
  sound: null | string;
  title: string;
}

export interface NotificationResult {
  apnsId: null | string;
  details: null | SentDetail[];
  error: ErrorData | null | string;
  errorData: ErrorData | null;
  errors: APNsError[] | null;
  failed: number;
  headers: null | Record<string, unknown>;
  response: null | RawResponse;
  responseBody: null | string;
  sent: number;
  status: null | number;
  statusCode: null | number;
  success: boolean;
}

export type {
  APNsError as Error,
  ErrorData,
  LibraryFailedItem,
  LibrarySentItem,
  RawResponse,
  SentDetail,
};
