import type { Options as CLIOptions } from '$generated/types';

export { CLIRunner, createRunner, sleep } from './runner';
export type { ExitCallback, OutputCallback } from './runner';

// Types generated by type-crafter
export type { CLIOptions };

// Types defined in YAML spec (cli.yaml) but not generated by type-crafter
// because they contain $ref or array constructs.
// TODO: Remove once type-crafter supports these constructs.
export interface CLICommand {
  args: string[];
  name: string;
  options: CLIOptions;
}

export interface CLIResult {
  error: null | string;
  exitCode: number;
  output: null | string;
  success: boolean;
}

export interface CLIRunnerConfig {
  args: null | string[];
  cols: null | number;
  command: string;
  cwd: null | string;
  rows: null | number;
  useLoginShell: boolean | null;
}

const DEFAULT_OPTIONS: CLIOptions = {
  dryRun: false,
  timeout: null,
  verbose: false,
};

export function createCommand(name: string, args: string[] = []): CLICommand {
  return {
    args,
    name,
    options: { ...DEFAULT_OPTIONS },
  };
}

export function createErrorResult(error: string, exitCode = 1): CLIResult {
  return {
    error,
    exitCode,
    output: null,
    success: false,
  };
}

export function createSuccessResult(output: string): CLIResult {
  return {
    error: null,
    exitCode: 0,
    output,
    success: true,
  };
}

export function formatCommand(command: CLICommand): string {
  const parts = [command.name, ...command.args];
  return parts.join(' ');
}

export function withOptions(command: CLICommand, options: Partial<CLIOptions>): CLICommand {
  return {
    ...command,
    options: {
      dryRun: options.dryRun !== undefined ? options.dryRun : command.options.dryRun,
      timeout: options.timeout !== undefined ? options.timeout : command.options.timeout,
      verbose: options.verbose !== undefined ? options.verbose : command.options.verbose,
    },
  };
}
